cumboto-interfaz/cumboto_Front-End/base/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from base.views import inicio
from base import views 


urlpatterns = [
	url(r'^$', views.inicio, name='inicio'),
]

cumboto-interfaz/cumboto_Front-End/biblioteca/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from .views import registrar_view, metadatos_get_data, listar_app_view, ListDataJsonView, zip_get_data, delete_get_data
from django.contrib.auth.decorators import login_required


app_name = 'biblioteca'

urlpatterns = [
    url(r'^biblioteca$', login_required(registrar_view.as_view()), name="subir"),
    url(r'^biblioteca/listar$', login_required(listar_app_view), name="listar"),
    url(r'^biblioteca/data$', login_required(ListDataJsonView.as_view()), name="listar_data"),
]

# Urls usadas para ajax
urlpatterns += [
    url(r'^ajax/metadatos-data$', login_required(metadatos_get_data) ,name="metadatos_data"),
    url(r'^biblioteca/ajax/delete-data$', login_required(delete_get_data) ,name="delete_data"),
    url(r'^ajax/enviar-zip$', login_required(zip_get_data) ,name="enviar_zip_data"),
]

cumboto-interfaz/cumboto_Front-End/biblioteca/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.files.base import File
from biblioteca.validators import valid_extension
import os
from sys import argv
from zipfile import BadZipfile, ZipFile
import urllib2, sys, zipfile
from shutil import * 


def generate_path(instance, filename):
    folder = os.path.join("tmp", filename)
    return folder


class registrar_app(models.Model):
    cargar_app = models.FileField(
        blank=True, null=True, upload_to=generate_path,
        validators=[valid_extension])

    def __unicode__(self):
        return self.cargar_app


class metadata_model(models.Model):
    nombre = models.CharField(max_length=25,)
    id_organizacion = models.CharField(max_length=25,)
    id_app = models.CharField(max_length=25, primary_key=True)
    codigo_app = models.CharField(max_length=25,)
    version = models.CharField(max_length=25,)
    clase_inicial = models.CharField(max_length=25,)

cumboto-interfaz/cumboto_Front-End/biblioteca/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from biblioteca.models import registrar_app
from django.utils.translation import ugettext_lazy as _


class registrar_form(ModelForm):
    """!
    Clase del formulario para registrar aplicaciones en la biblioteca
    Autor: Hugo Ramírez (hramirez@cenditel.gob.ve)
    Fecha: 2016
    """
    cargar_app = forms.FileField(label=("Cargar Aplicación"),widget=forms.FileInput(attrs={
        'class': 'filestyle',
        'type': 'file',
        'data-placeholder' : 'Archivos permitidos: .zip',
        'data-buttonName' : 'btn-default',
        'data-placement':'left',
        'data-toggle': 'tooltip',
        'data-buttonText': 'Buscar archivo',
        'data-classInput' : 'input-small',
        'data-size':'sm',
        'required': 'true',
        'title': _("Seleccione el archivo zip que contenga la aplicacion a registrar"),
       }))

    class Meta:
        model = registrar_app
        fields=['cargar_app']

cumboto-interfaz/cumboto_Front-End/biblioteca/views.py
# -*- coding: utf-8 -*-
import os , sys , codecs
import shutil
import zipfile
import re , configparser
import json
import requests
import random, struct
from django.conf import settings
from django.http import JsonResponse
from ConfigParser import ConfigParser
from django.shortcuts import render,  render_to_response
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader, Context, RequestContext
from django.contrib import messages
from django.views.generic.edit import FormView, CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic.edit import FormView
from .forms import registrar_form
from .models import registrar_app, metadata_model
from django_datatables_view.base_datatable_view import BaseDatatableView
import base64
from django.core.exceptions import ValidationError
from django.core import urlresolvers
from usuario.models import Bitacora
from datetime import datetime


class registrar_view(CreateView):
    """
    Clase que permite registrar una aplicación en la biblioteca
    Autor: Hugo Ramírez (hramirez@cenditel.gob.ve)
    Fecha: 2016
    """
    template_name= 'registro.template.html'
    form_class = registrar_form
    success_url = reverse_lazy('biblioteca:subir')

    '''
    def valid_extension(value):
        print "Entro en valid_extension----------"
        if (not value.name.endswith('.zip')):
            raise ValidationError("Archivos permitidos: .zip")

    def encrypt(value):
        print "Entro en encrypt----------"
        with open(value, "rb") as file_z:
            encoded = base64.b64encode(file_z.read())
            return True
    '''

    def form_valid(self, form):
        print "Entro en form_valid -------------------------\n"
        self.object = form.save(commit=False)
        self.object.cargar_app = form.cleaned_data['cargar_app']
        self.object.save()        
        namefile = form.cleaned_data['cargar_app'].name
        FilePath =('tmp/'+namefile)
        folders = []
        try:
            z = zipfile.ZipFile(open(FilePath,"rb"))
            for name in z.namelist():
                z.extract(name)
                if(name[-1] == "/"):
                    folders.append(name)
                metadata = name

            ##### Metadatos #####

            #ruta del directorio
            path = os.getcwd()
            Eliminar_zip = path+'/'+FilePath

            #Lista vacia para incluir los ficheros
            lstFiles = []

            #Lista con todos los ficheros del directorio:
            lstDir = os.walk(path)   #os.walk()Lista directorios y ficheros

            metadata = name
            name_dir = os.path.dirname(metadata)
            ruta = path+'/'+name_dir

            ### Valida que exista el archivo metadatos.conf y el directorio aplicacion
            metadatos = os.path.isfile(os.path.join(ruta, 'metadatos.conf'))
            aplicacion = os.path.isdir(os.path.join(ruta, 'aplicacion'))

            if metadatos == True and aplicacion == True:

                ### Contenedor ###
                metadata = name

                #### Leer Diccionario ####
                def leerDict(diccionario, elemento):
                    for i, j in elemento.items():
                        diccionario = diccionario.replace(i, j)
                    return diccionario

                #### Limpieza ####
                def limpieza(l):
                    v = True
                    while v == True:
                        try:
                            c= l.index ('')
                        except ValueError:
                            c = -1
                            v= False
                        if c > 0:
                            c = l.remove ('')

                #### Parsear los Metadatos ####
                def parsearFile(metadata):
                    libreria=[]
                    parserFile = open(metadata, 'r').read()
                    p = parserFile.split('\n')
                    configP = configparser.RawConfigParser()
                    parse = r""+metadata+""
                    configP.readfp(codecs.open(parse, "r", "utf8"))
                    limpieza(p)
                    for parsemeta  in range (len(p)):
                        if parsemeta == 0:
                            elementos = {'[':'',']':''}
                            result = leerDict(p[0], elementos)
                        if parsemeta > 0:
                            indicadores = {':':'','=':''}
                            dictParser = leerDict(p[parsemeta], indicadores)
                            c= dictParser.split()
                            e = configP.get(result, c[0])
                            e = e.split()
                            libreria.append({c[0] : e[0]})
                    return libreria
            else:
                form = registrar_form
                msg_error = 'El archivo No cumple con los requeisitos'
                os.remove(Eliminar_zip)
                return render(self.request, self.template_name, {'msg_error': msg_error, 'form': form})

            ### Codigo de la aplicacion ###
            name_dir = os.path.dirname(metadata)
            codigo_app = name_dir

            ### Eliminar Extraccion ###
            Eliminar = path+'/'+name_dir
           
            #### Json Metadatos ####
            md = parsearFile(metadata)

            ### Ruta zip ###
            absoluta = os.path.abspath(FilePath)

            if md:
                ####  VALIDATORS IF EXISTS COD IN DB ####
                try:
                    models = metadata_model
                    validator = models.objects.get(codigo_app = codigo_app)
                    if validator.codigo_app == codigo_app:
                        message = ('Desea reemplazar la aplicacion registrada ('+validator.nombre+') por la que se esta cargando ('+validator.nombre+')')

                    ide = md[2]
                    for ky, vl in ide.iteritems():
                        ide_app = vl

                    version = md[3]
                    for key, val in version.iteritems():
                        version_app = val

                    version_key = version.keys()
                    version_value = version.values()
                         
                    nombre = md[0]
                    for clave, valor in nombre.iteritems():
                        nombre_app = valor

                    nombre_key = nombre.keys()
                    nombre_value = nombre.values()

                    shutil.rmtree(Eliminar)

                    '''
                    Rutina que hace el envio del archivo a la capa de enlace para Actualziar [Update(crUd)]
                    Autor: Luis Guillermo Echenique lechenique@cenditel.gob.ve
                    Fecha: 22-05-2017
                    '''
                    url = settings.URL_API_REST+'archivo/'+ide_app+'/'
                    files = {'doc': open(absoluta, 'rb')}

                    r = requests.put(url,data = {'archivo_nombre': nombre_app, 'id_app':ide_app, 'version':version_app, 'codigo_app': codigo_app}, files=files)
                    if r.status_code==200:
                        os.remove(absoluta)

                    print "----- Envio del archivo a la capa de enlace para actualizar!!! -----"
                    return render(self.request, self.template_name, {'form': form , 'metadatos': json.dumps(md) , 'codigo_app': codigo_app ,'version_app': version_app, 'nombre_app': nombre_app, 'id': ide_app, 'MSG': message , 'absoluta': absoluta })

                except models.DoesNotExist:
                    ide = md[2]
                    for ky, vl in ide.iteritems():
                        ide_app = vl

                    version = md[3]
                    for key, val in version.iteritems():
                        version_app = val

                    version_key = version.keys()
                    version_value = version.values()
                         
                    nombre = md[0]
                    for clave, valor in nombre.iteritems():
                        nombre_app = valor

                    nombre_key = nombre.keys()
                    nombre_value = nombre.values()
                    message = ('Desea realizar el registro de la aplicacion ('+nombre_app+')')

                    shutil.rmtree(Eliminar)
                    
                    '''
                    Rutina que hace el envio del archivo a la capa de enlace 
                    Autor: Luis Guillermo Echenique lechenique@cenditel.gob.ve
                    Fecha: 22-05-2017
                    '''
                    url = settings.URL_API_REST+'archivo/'
                    files = {'doc': open(absoluta, 'rb')}

                    r = requests.post(url,data = {'archivo_nombre': nombre_app, 'id_app':ide_app, 'version':version_app, 'codigo_app': codigo_app}, files=files)
                    if r.status_code==201:
                        os.remove(absoluta)
                    print "----- Envio del archivo a la capa de enlace!!! -----"
                    return render(self.request, self.template_name, {'form': form , 'metadatos': json.dumps(md) , 'codigo_app': codigo_app ,'version_app': version_app, 'nombre_app': nombre_app, 'id': ide_app, 'MSG': message ,  })
            else:
                form = registrar_form
                msg_error = 'El archivo No cumple con los requeisitos'
                return render(self.request, self.template_name, {'msg_error': msg_error, 'form': form})

        except zipfile.BadZipfile, err:
            form = registrar_form
            msg_error = 'El archivo no es un .zip'
            return render(self.request, self.template_name, {'msg_error': msg_error, 'form': form})  


def metadatos_get_data(request):
    nombre = request.GET.get('nombre', None)
    id_organizacion = request.GET.get('id_organizacion', None)

cumboto-interfaz/cumboto_Front-End/biblioteca/templates/listar.template.html
{% extends "base.template.html" %}
{% load staticfiles %}
{% block content %}
<script type="text/javascript">
$(document).ready(function() {
    $(".alert-success").fadeTo(2000, 500).slideUp(200, function(){
        $(".alert-success").slideUp(10);
    });
    var selected = [];
    var valboton = 0;
    /**
    * Se crea la variable table, se vincula con el elemento #datatable y se inicializa consumiendo los datos del
    * API-Rest junto con la creación de un botón único a cada fila
    * Autor: Luis Guillermo Echenque (lechenique@gmail.com)
    * Fecha: 22-05-2017
    */
    var table = $("#datatable").DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{% url 'biblioteca:listar_data' %}",
        "columns": [
            null,
            null,
            null,
            null,
            {
                "targets": -1,
                "data": null,
                "render" : function(type, full, row, meta) {
                    var id = meta.row;
                    return '<button type="button" class="btn btn-default btn-circle"  data-toggle="tooltip" data-placement="top" title="Seleccione una fila de la tabla para eliminar" align="rigth" id="boton'+id+'" disabled><i class="fa fa-trash-o" aria-hidden="true"></i></button>'
                }
            }
        ],
        "rowCallback": function( row, data ) {
            if ( $.inArray(data.DT_RowId, selected) !== -1 ) {
                $(row).addClass('selected');
            }
        }
    });
    

    /**
    * Se crea la secuencia de seleccion de las filas y la interacción con el valor del boton
    * Autor: Luis Guillermo Echenque (lechenique@gmail.com)
    * Fecha: 22-05-2017
    */
    $('#datatable')
        .addClass('table table-striped table-bordered dt-responsive nowrap');
    $('#datatable tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
            $("#boton"+valboton).prop("disabled", true);
            $("#boton"+valboton).removeClass("btn btn-default btn-circle btn-danger").addClass("btn btn-default btn-circle");

        }
        else {
            $("#boton"+valboton).removeClass("btn btn-default btn-circle btn-danger").addClass("btn btn-default btn-circle");
            $("#boton"+valboton).prop("disabled", true);
            valboton = table.row( this ).index();
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            $("#boton"+valboton).prop("disabled", false);
            $("#boton"+valboton).removeClass("btn btn-default btn-circle").addClass("btn btn-default btn-circle btn-danger");

        }
    });


    /**
    * Función que permite eliminar los valores de la fila en el API-Rest y actualiza la vista de la tabla
    * Autor: Luis Guillermo Echenque (lechenique@gmail.com)
    * Fecha: 22-05-2017
    */
    $('#datatable tbody').on( 'click', 'button', function () {
        var data = table.row('.selected').index();
        var a = table.row('.selected').data();
        var id = a[0]
            var codigo = a[1]
            var nombre = a[2]
            $.ajax({
                url:'ajax/delete-data',
                data:{'id': id, 'codigo': codigo, 'nombre': nombre},
                type:'get',
            });
        table.ajax.reload();
        window.location.reload();

    } );

});
</script>

<div class="page-title">
    <div class="title_left">
        <h3>Gestión de Transmisión de Aplicaciones Interactivas para la TDA</h3>
    </div>
</div>
<div class="x_panel">
    {% if messages %}
    <div class="alert alert-success alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ messages }}</strong>
    </div>
    {% endif %}
    <div class="row">
        <br>
        <div class="col-md-4">
            <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
        </div>
        <div class="col-md-8"></div>
    </div>
    <br>
    <div class="row">
        <div class="col-xs-1"></div>
        <div class="mensaje"></div>
        <div class="col-xs-10">
            <h1 align="center">Lista de Aplicaciones</h1><hr><br>
            <table id="datatable" cellspacing="0" width="100%" style="text-align: center;" >
                <thead>
                    <tr align="center">
                        <th style="text-align: center">id</th>
                        <th style="text-align: center">codigo aplicacion</th>
                        <th style="text-align: center">nombre</th>
                        <th style="text-align: center">version</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="col-xs-1"></div>
    </div>
</div>

{% endblock %}

cumboto-interfaz/cumboto_Front-End/biblioteca/templates/metadata.messages.html
{% load i18n %}
{% if metadatos %}
      <script type="text/javascript">
          var msg = "{{ metadatos }}";
          var modal = bootbox.dialog({
              message: msg,
              title: "Metadatos-Aplicacion",
              buttons: {
                  success: {
                      label: "Cerrar",
                      className: "btn-success",
                      callback: function() {

                      }
                  }
              }
          });
          $(modal).find(".bootbox-body").addClass('text-justify');


          var x = {{metadatos | safe }};
          $('#metadata').click(function(){
            var nombre = x[0].nombre
            var id_organizacion = x[1].id_organizacion
            var id = x[2].id
            var version = x[3].version
            var clase_inicial = x[4].clase_inicial

            $.ajax({url:'ajax/metadatos-data',data:{'nombre': nombre, 'id_organizacion': id_organizacion, 'id': id , 'version':version, 'clase_inicial':clase_inicial},type:'get',
              success:function(data){
                var error = bootbox.dialog({
                  title: 'Alertas',
                  message: 'Exito Al Enviar Data',
                  buttons: {
                    main: {
                      label: 'OK' ,
                      className: "btn btn-primary btn-sm"
                    }
                  }
                });
              },
              error:function(error)
              {
                var error = bootbox.dialog({
                  title: 'Alertas',
                  message: 'Error Al Enviar Data',
                  buttons: {
                    main: {
                      label: 'OK',
                      className: "btn btn-primary btn-sm"
                    }
                  }
                });
              },
            });
      </script>
{% endif %}

cumboto-interfaz/cumboto_Front-End/biblioteca/templates/metadatos.template.html
{% extends "base.template.html" %}
{% load staticfiles %}
{% block content %}
<div class="page-title">
    <div class="title_left">
        <h3>Gestión de Transmisión de Aplicaciones Interactivas para la TDA</h3>
    </div>
</div>
<div class="x_panel">
        <div class="row">
                <br>
                <div class="col-md-4">
                   <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
                </div>
                <div class="col-md-8"></div>
           </div>
            <div class="row">
                <div class="col-xs-3"></div>
                <div class="col-xs-6" style="">
                 <!-- Modal metadatos -->
                            <div class="modal fade bs-example-modal-sm" id="metadata" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                                      </button>
                                      <h4 class="modal-title" id="myModalLabel2">Metadatos</h4>
                                    </div>
                                    <div class="modal-body">
                                     {% if metadatos %}
                                     <script type="text/javascript">
                                     $(window).load(function(){
                                      $('#metadata').modal('show');
                                        });
                                     </script>
                                        {{ metadatos }}
                                        {% endif %}

                                    </div>
                                  <div class="modal-footer">
                                      <button type="submit" class="btn btn-default" id="metadata">Guardar</button>
                                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                  </div>
                                  </div>
                                </div>
                            </div>
                <!-- Fin modal metadatos -->
                </div>
                <div class="col-xs-3"></div>
            </div>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <br><br><br>
     
</div>
{% endblock %}