cumboto-interfaz/cumboto_Front-End/base/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from base.views import inicio
from base import views 


urlpatterns = [
	url(r'^$', views.inicio, name='inicio'),
]

cumboto-interfaz/cumboto_Front-End/biblioteca/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from .views import registrar_view, metadatos_get_data, listar_app_view, ListDataJsonView, zip_get_data, delete_get_data
from django.contrib.auth.decorators import login_required


app_name = 'biblioteca'

urlpatterns = [
    url(r'^biblioteca$', login_required(registrar_view.as_view()), name="subir"),
    url(r'^biblioteca/listar$', login_required(listar_app_view), name="listar"),
    url(r'^biblioteca/data$', login_required(ListDataJsonView.as_view()), name="listar_data"),
]

# Urls usadas para ajax
urlpatterns += [
    url(r'^ajax/metadatos-data$', login_required(metadatos_get_data) ,name="metadatos_data"),
    url(r'^biblioteca/ajax/delete-data$', login_required(delete_get_data) ,name="delete_data"),
    url(r'^ajax/enviar-zip$', login_required(zip_get_data) ,name="enviar_zip_data"),
]

cumboto-interfaz/cumboto_Front-End/usuario/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from usuario.forms import LoginForm
from django.contrib.auth.views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .forms import PasswordResetForm
from .views import *
from . import views
from usuario.views import *

app_name = 'usuario'

urlpatterns = [
    url(r'^login/$', views.acceso, name='acceso'),
    url(r'^bienvenido/$', login_required(inicio), name='inicio'),
    url(r'^crear_usuario/$', UsuarioCreate.as_view(), name='registro'),
    url(r'^perfil/(?P<pk>\d+)$', login_required(views.edit_profile), name="perfil"),
    url(r'^bitacora', login_required(views.BitacoraView.as_view()), name='bitacora'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^adminuser/$', login_required(useractive), name='adminuser'),
    url(r'^changestatus/', login_required(changestatus), name='changestatus'),
    url(r'^admdelusers/$', login_required(deleteusers), name='admdelusers'),
    url(r'^admedusers/$', login_required(editusers), name='admedusers'),
    url(r'^admedclav/$', login_required(editclav), name='admedclav'),
    url(r'^deluser/$', login_required(deluser), name='deluser'),
    url(r'^ediuserone/$', login_required(ediuserone), name='ediuserone'),
    url(r'^ediusertwo/$', login_required(ediusertwo), name='ediusertwo'),
    url(r'^ediclavone/$', login_required(ediclavone), name='ediclavone'),
    url(r'^ediclavtwo/$', login_required(ediclavtwo), name='ediclavtwo'),
    url(r'^password/$', login_required(views.change_password), name='change_password'),
    url(r'^reset/password_reset/$', password_reset, {'template_name': 'password_reset_form.html', 
        'email_template_name':'password_reset_email.html', 'password_reset_form':PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, {'template_name': 'password_reset_done.html'}, 
        name='password_reset/done/'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 
        password_reset_confirm, {'template_name': 'password_reset_confirm.html'}, 
        name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'password_reset_complete.html'}, 
        name='password_reset_complete'),
]

cumboto-interfaz/cumboto_Front-End/base/models.py
from django.db import models

# Create your models here.

cumboto-interfaz/cumboto_Front-End/base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,  render_to_response
from django.template import loader, Context,  RequestContext
from django.core.urlresolvers import reverse_lazy


@login_required
def inicio(request):
    return render_to_response('home.template.html', {}, context_instance=RequestContext(request))

cumboto-interfaz/cumboto_Front-End/base/templates/base.alert.messages.html
{% load i18n %}
{% for message in messages %}
    {% if message %}
        <script type="text/javascript">
            var msg = "{{ message }}";
            var modal = bootbox.dialog({
                message: msg,
                title: "{% trans 'Aviso' %}",
                buttons: {
                    success: {
                        label: "{% trans 'Cerrar' %}",
                        className: "btn-success",
                        callback: function() {

                        }
                    }
                }
            });
            $(modal).find(".bootbox-body").addClass('text-justify');
        </script>
    {% endif %}
{% endfor %}

cumboto-interfaz/cumboto_Front-End/base/templates/base.footer.template.html
{% load static from staticfiles %}
{% load i18n %}
    <!-- Bootstrap Switch (requerido) -->
    <script src="{% static 'vendors/bootstrap-switch-3.3.2/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
    <!-- Manual de Usuario Dinamico -->
    <script src="{% static 'js/manual.js' %}"></script>
    <!-- Funciones especiales -->
    <script src="{% static 'js/funciones.js' %}"></script>
    <!-- Bootbox -->
    <script src="{% static 'vendors/bootbox/bootbox.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
   <!-- Custom Theme Scripts 
   <script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>-->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-filestyle.js' %}"></script>
    <script src="{% static 'js/bootstrap-filestyle.min.js' %}"></script>
    <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>

    <!-- Datatables -->
    <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'vendors/jszip/dist/jszip.min.js' %}"></script>
    <!--
    <script src="{% static 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>
    -->

    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>

     <!-- Datatables -->
    <script>

      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').dataTable();

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'asc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-orange'
          });
        });

        TableManageButtons.init();
      });
    </script>
    <!-- /Datatables -->

cumboto-interfaz/cumboto_Front-End/base/templates/base.form.errors.html
{% load i18n %}
{% if form_errors %}
    <div class="error-notice">
        <div class="oaerror danger">
            <div class="row">
                <div class="{% if not col_title_error %}col-sm-3{% else %}{{ col_title_error }}{% endif %}">
                    <strong>{% trans 'Error' %}</strong>
                </div>
                <div class="{% if not col_msg_error %}col-sm-9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>

        </div>
    </div>
{% endif %}

cumboto-interfaz/cumboto_Front-End/base/templates/base.head.template.html
{% load static from staticfiles %}
{% load i18n %}
<head>
	<meta charset="UTF-8">
	<title>{% trans '' %}</title>
	<meta name="robots" content="noindex, nofollow">
	<meta name="author" content="Cenditel">
  <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
	<meta name="author" content="{% trans 'Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL)' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cumboto</title>
    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">
    <!-- Switchery -->
    <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
    
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap-switch (requerido) -->
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-switch-3.3.2/css/bootstrap3/bootstrap-switch.min.css' %}"/>
    <!-- Datatables -->
    <link href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">
    <!-- Own styles - css-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css'%}" rel="stylesheet">
     <style type="text/css">

        .x_panel {
            background: url({% static 'img/fondo_cumboto4.png' %});
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            text-align: center;
            height: 100%;
            width: 100%;
            margin: 0px;
            background-position: center;
        }
        .btn-circle.btn-xl{
          width: 70px;
          height: 70px;
          padding: 10px 16px;
          font-size: 24px;
          line-height: 1.33;
          border-radius: 35px;
        }
        .btn-circle {
          width: 30px;
          height: 30px;
          text-align: center;
          padding: 6px 0;
          font-size: 12px;
          line-height: 1.428571429;
          border-radius: 15px;
        }
        .oaerror {
          margin: 0 auto; /* Centering Stuff */
          background-color: #FFFFFF; /* Default background */
          padding: 5px;
          border: 1px solid #eee;
          border-left-width: 5px;
          border-radius: 3px;
          font-family: 'Open Sans', sans-serif;
          font-size: 12px;
          color: grey;
        }
        .oaerror ul {
            display: inline-block;
            padding-left: 0;
        }
        .oaerror ul li {
            list-style: none;
            text-align: justify;
        }
        .danger {
          border-left-color: #d9534f; /* Left side border color */
          background-color: rgba(217, 83, 79, 0.1); /* Same color as the left border with reduced alpha to 0.1 */
        }

        .danger strong {
          color:  #d9534f;
        }

        .warning {
          border-left-color: #FF6600;
          background-color: rgba(255, 102, 0, 0.1);
        }

        .warning strong {
          color: #FF6600;
        }

        .info {
          border-left-color: #5bc0de;
          background-color: rgba(91, 192, 222, 0.1);
        }

        .info strong {
          color: #5bc0de;
        }

        .success {
          border-left-color: #2b542c;
          background-color: rgba(43, 84, 44, 0.1);
        }

        .success strong {
          color: #2b542c;
        }

     </style>
</head>
	

cumboto-interfaz/cumboto_Front-End/base/templates/base.template.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="es">
{% include 'base.head.template.html' %}
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'inicio' %}" class="site_title"><img src="{% static 'img/logo.png' %}"><span>cumboto</span></a>
            </div>

            <div class="clearfix"></div>
            <!-- Panel Menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="{% url 'usuario:perfil' user.id%}"><i class="fa fa-user"></i>Perfil</a></li>
                  {% if user.is_superuser %}
                  <!-- Gestion de Usuarios - Menu -->
                  <li>
                    <a><i class="fa fa-users"></i> Gestion de Usuarios <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li class="sub_menu"><a href="{% url 'usuario:adminuser' %}">Control de usuarios</a></li>
                    </ul>
                  </li>
                  {% endif %}
                  <!-- Biblioteca -->
                  <li><a><i class="fa fa-desktop"></i>Biblioteca<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'biblioteca:subir' %}"><i class="fa fa-edit"></i>Registrar Aplicaciones</a></li>
                      <li><a href="{% url 'biblioteca:listar' %}"><i class="fa fa-list-alt"></i>Listar Aplicaciones</a></li>
                    </ul>
                  </li>
                  <!-- Servicios -->
                  <li><a><i class="fa fa-cogs"></i>Servicios<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'servicios:global' %}"><i class="fa fa-cog"></i>Configurar Servicio Emergente</a></li>
                      <li><a href="{% url 'servicios:app_omision' %}"><i class="fa fa-cogs"></i>Configurar Aplicacion por Omision</a></li>
                      <li><a href="{% url 'servicios:rest_consulta' %}"><i class="fa fa-eye"></i>Consulta de Servicios</a></li>
                    </ul>
                  </li>
                  <!-- Agenda --> 
                  <li><a href="#"><i class="fa fa-calendar"></i>Agenda<span class="fa fa-chevron-down"></span></a>
                  {% if user.is_superuser %}
                    <li><a href="{% url 'usuario:bitacora' %}"><i class="fa fa-eye"></i>Bitácora de Eventos</a></li>
                  {% else %}
                  {% endif %}
                  </li>
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'usuario:logout' %}"><i class="fa fa-sign-out"></i>Cerrar Sesión</a></li>
                  {% endif %}
                </ul>

              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="#" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                     {{ user.username }}  <i  class="fa fa-user" ></i> <span class="fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    {% if user.is_authenticated %}
                    <li>
                      <a href="{% url 'usuario:perfil' user.id%}">
                        <i class="fa fa-user"></i>
                        Perfil
                      </a>
                    </li>
                    <li>
                      <a href="{% url 'usuario:logout' %}">
                        <i class="fa fa-sign-out pull-left"></i>
                        Cerrar Sesión
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          {% block content %}
            
          {% endblock %} 
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
</body>
{% include 'base.footer.template.html' %}
</html>

cumboto-interfaz/cumboto_Front-End/base/templates/home.template.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block content %}
<div class="page-title">
    <div class="title_left">
        <h3>Gestión de Transmisión de Aplicaciones Interactivas para la TDA</h3>
    </div>
</div>
     <div class="x_panel">
     <div class="row">
              <br>
              <div class="col-md-4">
                   <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
              </div>
              <div class="col-md-8"></div>
           </div>
           <div class="row" id="manual">
           <div class="col-md-2"></div>
           <div class="col-md-8">
           <br><h1 align="center">Manual De Usuario</h1><hr><br>
           <div class="row">
               <div class="col-md-2"></div>
               <div class="col-md-4">
                   <!-- Modal usuario-->
                   <div class="modal fade" id="ModalUsuario" role="dialog">
                      <div class="modal-dialog">
                         <!-- Modal contenido-->
                         <div class="modal-content">
                           <div class="modal-header">
                               <button type="button" class="close" data-dismiss="modal">&times;</button>
                               <h2 class="modal-title">Información</h2>
                           </div>
                           <div class="modal-body">
                               <p>Modulo Gestion de Usuario.</p>
                           </div>
                           <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Gracias</button>
                           </div>
                         </div>
                       </div>
                    </div>
                    <button type="button" class="btn btn-default btn-circle btn-xl" id="BtnUsuario"><i class="glyphicon glyphicon-user"></i></button>
               </div>
               
               <div class="col-md-4">
                   <!-- Modal Biblioteca -->
                   <div class="modal fade" id="ModalBiblioteca" role="dialog">
                      <div class="modal-dialog">
                         <!-- Modal contenido-->
                         <div class="modal-content">
                           <div class="modal-header">
                               <button type="button" class="close" data-dismiss="modal">&times;</button>
                               <h4 class="modal-title">Información</h4>
                           </div>
                           <div class="modal-body">
                               <p>Modulo Biblioteca.</p>
                           </div>
                           <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Gracias</button>
                           </div>
                         </div>
                       </div>
                    </div>
                   <button type="button" class="btn btn-default btn-circle btn-xl" id="BtnBiblioteca"><i class="glyphicon glyphicon-folder-open"></i></button>
               </div>
               <div class="col-md-2"></div>
            </div>
            <br><br>
            <div class="row">
            <div class="col-md-2"></div>
               <div class="col-md-4">
               <!-- Modal Configuración de Servicios -->
                   <div class="modal fade" id="ModalServicios" role="dialog">
                      <div class="modal-dialog">
                         <!-- Modal contenido-->
                         <div class="modal-content">
                           <div class="modal-header">
                               <button type="button" class="close" data-dismiss="modal">&times;</button>
                               <h4 class="modal-title">Información</h4>
                           </div>
                           <div class="modal-body">
                               <p>Modulo Configuración de Servicios.</p>
                           </div>
                           <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Gracias</button>
                           </div>
                         </div>
                       </div>
                    </div>
                   <button type="button" class="btn btn-default btn-circle btn-xl" id="BtnServicios"><i class="glyphicon glyphicon-cog"></i></button>
               </div>

               <div class="col-md-4">
               <!-- Modal Agenda Programada -->
                   <div class="modal fade" id="ModalAgenda" role="dialog">
                      <div class="modal-dialog">
                         <!-- Modal contenido-->
                         <div class="modal-content">
                           <div class="modal-header">
                               <button type="button" class="close" data-dismiss="modal">&times;</button>
                               <h4 class="modal-title">Información</h4>
                           </div>
                           <div class="modal-body">
                               <p>Modulo Agenda Programada.</p>
                           </div>
                           <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Gracias</button>
                           </div>
                         </div>
                       </div>
                    </div>
                   <button type="button" class="btn btn-default btn-circle btn-xl" id="BtnAgenda"><i class="glyphicon glyphicon-calendar"></i></button>
               </div>
            <div class="col-md-2"></div>
            </div>
            </div>
            <div class="col-md-2"></div>
            </div>

            <br><br><br><br>
            <br><br><br><br>
            <br><br><br><br>
     </div>
{% endblock %}