cumboto-interfaz/cumboto_Front-End/base/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from base.views import inicio
from base import views 


urlpatterns = [
	url(r'^$', views.inicio, name='inicio'),
]

cumboto-interfaz/cumboto_Front-End/cumboto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from base.views import inicio


urlpatterns = [
    url(r'^cumboto/admin/', admin.site.urls),
    url(r'^cumboto/', include('base.urls', namespace='base', app_name='base')),
    url(r'^$',inicio, name='inicio'),
    url(r'^cumboto/', include('usuario.urls',namespace='usuario')),
    url(r'^cumboto/', include('biblioteca.urls', namespace='biblioteca')),
    url(r'^cumboto/', include('servicio.urls', namespace='servicios')),
    #url(r'^', include('agenda.urls')),
    url(r'^cumboto/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cumboto-interfaz/cumboto_Front-End/usuario/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, patterns
from usuario.forms import LoginForm
from django.contrib.auth.views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .forms import PasswordResetForm
from .views import *
from . import views
from usuario.views import *

app_name = 'usuario'

urlpatterns = [
    url(r'^login/$', views.acceso, name='acceso'),
    url(r'^bienvenido/$', login_required(inicio), name='inicio'),
    url(r'^crear_usuario/$', UsuarioCreate.as_view(), name='registro'),
    url(r'^perfil/(?P<pk>\d+)$', login_required(views.edit_profile), name="perfil"),
    url(r'^bitacora', login_required(views.BitacoraView.as_view()), name='bitacora'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^adminuser/$', login_required(useractive), name='adminuser'),
    url(r'^changestatus/', login_required(changestatus), name='changestatus'),
    url(r'^admdelusers/$', login_required(deleteusers), name='admdelusers'),
    url(r'^admedusers/$', login_required(editusers), name='admedusers'),
    url(r'^admedclav/$', login_required(editclav), name='admedclav'),
    url(r'^deluser/$', login_required(deluser), name='deluser'),
    url(r'^ediuserone/$', login_required(ediuserone), name='ediuserone'),
    url(r'^ediusertwo/$', login_required(ediusertwo), name='ediusertwo'),
    url(r'^ediclavone/$', login_required(ediclavone), name='ediclavone'),
    url(r'^ediclavtwo/$', login_required(ediclavtwo), name='ediclavtwo'),
    url(r'^password/$', login_required(views.change_password), name='change_password'),
    url(r'^reset/password_reset/$', password_reset, {'template_name': 'password_reset_form.html', 
        'email_template_name':'password_reset_email.html', 'password_reset_form':PasswordResetForm},
        name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, {'template_name': 'password_reset_done.html'}, 
        name='password_reset/done/'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 
        password_reset_confirm, {'template_name': 'password_reset_confirm.html'}, 
        name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'password_reset_complete.html'}, 
        name='password_reset_complete'),
]

cumboto-interfaz/cumboto_Front-End/usuario/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class Perfil(models.Model):
    """
    Modelo para guardar el Perfil de usuario
    Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
    Fecha: 06-06-2017
    """

    # Establece la relación entre el usuario de Django y el perfil.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Establece el Cargo que ocupa el usuario.
    cargo = models.CharField(max_length=50)

    def __unicode__(self):
        return self.cargo


class Bitacora(models.Model):
    """
    Modelo para guardar la bitácora de acciones del usuario
    Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
    Fecha: 06-07-2017
    """
    # Establece el usuario que realizó la acción.
    usuario=models.CharField(max_length=200)

    # Breve descripción de la acción realizada.
    descripcion = models.CharField(max_length=200)

    # Establece el tipo de acción realizada (acceso, etc)
    tipo = models.CharField(max_length=50)

    # Establece la fecha y hora en que se realizó la acción.
    fecha_hora = models.CharField(max_length=50)

    def __unicode__(self):
        return self.usuario

cumboto-interfaz/cumboto_Front-End/usuario/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader, Context,  RequestContext
from django.contrib.auth.models import User
from .forms import *
from django.contrib.auth.hashers import make_password
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.views.generic import TemplateView, FormView, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.core import urlresolvers
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.messages.storage.cookie import CookieStorage
from django.views.generic import TemplateView, CreateView, ListView
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.template import loader, Context
from django.views import generic
from django.views.generic import DeleteView
import logging
from django.contrib.auth import forms, login, logout, authenticate
from django.contrib.auth.tokens import default_token_generator
logger = logging.getLogger("usuario")
from datetime import datetime
from .models import Perfil, Bitacora

class IndexTemplate(TemplateView):
   template_name = "home.template"

def acceso(request):
    """
    Función que gestiona la autenticación de los usuarios, maneja estatus de no logeado, inactivo en espera de activación y sin usuario creado.
    Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
    Fecha: 13-02-2017
    """
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid:
            usuario = request.POST['username']
            clave = request.POST['password']
            acceso = authenticate(username=usuario, password=clave)
            if acceso is not None:
                if acceso.is_active:
                    login(request, acceso)
                    Bitacora.objects.create(usuario=request.user, descripcion='Accedio al sistema', tipo='Acceso', fecha_hora=datetime.now())
                    return HttpResponseRedirect(urlresolvers.reverse('usuario:inicio'))
                else:
                    messages = ['Lo sentimos, este usuario está en espera de activación']
                    return render_to_response('base.login.html', {'form': form, 'messages': messages}, context_instance=RequestContext(request))
            else:
                messages = ['Lo sentimos, el usuario o la contraseña no son válidos. Vuelve a intentarlo.']
                return render_to_response('base.login.html', {'form': form, 'messages': messages}, context_instance=RequestContext(request))
    else:
        form = AuthenticationForm()

    return render_to_response('base.login.html', {'form': form}, context_instance=RequestContext(request))

def inicio(request):
    """
    Función que abre pagina de inicio.
    Autor: Etzel Mencias
    Fecha: 31 octubre 2017
    """
    users = User.objects.order_by('-pk')
    return render_to_response('home.template.html',context_instance=RequestContext(request))

def logout_view(request):
    """
    Función que permite cerrar la sesión del usuario
    Autor: Hugo Ramírez (hramirez@cenditel.gob.ve)
    Fecha: 2016
    """
    user = request.user
    if user.is_authenticated():
        logout(request)
    return redirect(reverse('login'))


class UsuarioCreate(SuccessMessageMixin,CreateView):
    """
    Clase que registra los usuarios del sistema
    Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
    Fecha: 22-05-2017
    """
    model = User
    form_class = UserForm
    template_name = "registro.html"
    success_url = reverse_lazy('usuario:acceso')
    success_message = "¡Registro exitoso! debe esperar la activacion de su cuenta"

    def form_valid(self,form):
        """
        Método que verifica si el formulario es válido, en cuyo caso procede a registrar los datos del usuario.
        Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
        Fecha: 22-05-2017
        """
        self.object = form.save(commit=False)
        self.object.username = form.cleaned_data['username']
        self.object.first_name = form.cleaned_data['first_name']
        self.object.last_name = form.cleaned_data['last_name']
        self.object.set_password(form.cleaned_data['password1'])
        self.object.email = form.cleaned_data['email']
        self.object.is_active = 0
        self.object.save()

        # Registro de los campos extra del perfil del usuario
        perfil = Perfil()
        perfil.cargo = form.cleaned_data['cargo']
        perfil.user = self.object
        perfil.save()

        return super(UsuarioCreate, self).form_valid(form)


def edit_profile(request, pk):
    """
    Función que permite editar el perfil del usuarios autenticado.
    Autor: Argenis Osorio (aosorio@cenditel.gob.ve)
    Fecha: 20-03-2017
    """
    user = User.objects.get(pk=request.user.pk)
    if request.method == 'GET':
        form = EditProfileForm(instance=user)
    else:
        form = EditProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
        messages = '¡Perfil actualizado!'
        Bitacora.objects.create(usuario=request.user, descripcion='Actualizó el perfil', tipo='Actualización', fecha_hora=datetime.now())
        return render_to_response('user_profile.html', {'form': form, 'messages': messages}, context_instance=RequestContext(request))
    return render(request, 'user_profile.html', {'form':form})


def useractive(request):
    users = User.objects.order_by('-pk')
    if request.user.is_superuser:
        return render(request, 'admin.template.html', {"users": users})
    else:
        return render_to_response('home.template.html',context_instance=RequestContext(request))


def changestatus(request):
    """
    Funcion que activa, desactiva usuario y envia correo de confirmación
    Autor: Yngris Ibarguen (yibarguen@cenditel.gob.ve)
    Fecha: 2016
    Modificado: 2017
    """
    if request.method == 'POST':
        #obtengo el id del usuario 
        usuario = request.POST['idusuario']
        try:
            Usuario = User.objects.get(pk=usuario)
        except User.DoesNotExist:
            Usuario = None
        if (Usuario != None):
            if Usuario.is_active:
                Usuario.is_active = False
            else:
                Usuario.is_active = True
            dat_user = Usuario
            dat_user.save()
            
            if Usuario.is_active:
                email_subject = 'Cuenta activada'
                to_email = dat_user.email
                email_body = loader.get_template('mensaje-activacion.html').render(dict({'dat_user': dat_user}))
                send_mail(email_subject, email_body, settings.EMAIL_HOST_USER,
                [to_email], fail_silently=False)
            else:
                email_subject = 'Cuenta desactivada'
                to_email = dat_user.email
                email_body = loader.get_template('mensaje-desactivacion.html').render(dict({'dat_user': dat_user}))
                send_mail(email_subject, email_body, settings.EMAIL_HOST_USER,
                [to_email], fail_silently=False)

    return HttpResponseRedirect(urlresolvers.reverse('usuario:adminuser'))

def deleteusers(request):
    """
    Función que abre pagina para eliminar un usuario.
    Autor: Etzel Mencias
    Fecha: Mayo 2017
    """
    users = User.objects.order_by('-pk')
    if request.user.is_superuser:
        return render(request, 'admin.deleteusers.html', {"users": users})
    else:
        return render_to_response('home.template.html',context_instance=RequestContext(request))

def editusers(request):
    """
    Función que abre pagina para editar el correo de un usuario.
    Autor: Etzel Mencias
    Fecha: Mayo 2017
    """
    users = User.objects.order_by('-pk')
    if request.user.is_superuser:
        return render(request, 'admin.editusers.html', {"users": users})
    else:
        return render_to_response('home.template.html',context_instance=RequestContext(request))

def editclav(request):
    """
    Función que abre pagina para editar la contraseña de un usuario.
    Autor: Etzel Mencias
    Fecha: Junio 2017
    """
    users = User.objects.order_by('-pk')
    if request.user.is_superuser:
        return render(request, 'admin.editclave.html', {"users": users})
    else:
        return render_to_response('home.template.html',context_instance=RequestContext(request))

def deluser(request):
    """
    Función que elimina un usuario y avisa por correo.
    Autor: Etzel Mencias
    Fecha: Mayo 2017
    """
    if request.method == 'POST':
        usuario = request.POST['idusuario']
        try:
            Usuario = User.objects.get(pk=usuario)
        except User.DoesNotExist:
            Usuario = None
        if (Usuario != None):
            dat_user = Usuario
            dat_user.save()
            email_subject = 'Cuenta eliminada'
            to_email = dat_user.email
            email_body = loader.get_template('mensaje-eliminacion.html').render(dict({'dat_user': dat_user}))
            send_mail(email_subject, email_body, settings.EMAIL_HOST_USER, [to_email], fail_silently=False)
            Usuario.delete()
    return HttpResponseRedirect(urlresolvers.reverse('usuario:adminuser'))

def ediuserone(request):
    """
    Función 01 para editar el correo de un usuario.
    Autor: Etzel Mencias
    Fecha: Mayo 2017
    """
    if request.method == 'POST':
        idus = request.POST['idusuario']
        try:

cumboto-interfaz/cumboto_Front-End/usuario/templates/admin.deleteusers.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block content %}
<script type='text/javascript'>
$(document).ready(function() {
  $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {
    var data_id = '';
    if (typeof $(this).data('user-id') !== 'undefined') {
      data_id = $(this).data('user-id');
    }
    $('#idusuario').val(data_id);
  });
  })
</script>
<script>
$('#myModal').on('hidden', function () {
  document.location.reload();
})
</script>
      <div class="x_panel">
       <div class="row">
                <br>
                <div class="col-md-4">
                   <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
                </div>
                <div class="col-md-8"></div>
           </div>
      <div class="row">
      <div class="col-md-12" align="center">
      <h1>Eliminar Usuarios</h1>
        <hr>
         <form action="" method="post">
                   {% csrf_token %}
              <table class="table table-bordered">
                  <tr>
                    <th align="center">Usuario</th>
                    <th align="center">Nombres</th>
                    <th align="center">Apellidos</th>
                    <th align="center">Correo</th>
                    <th align="center">Estatus</th>
                    <th align="center">Opciones</th>
                  </tr>
              {% for u in users %}
              {% if u.is_active%}
              <tr class="bg-success">
                    <td>{{u.username}}</td>
                    <td>{{u.first_name}}</td>
                    <td>{{u.last_name}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
              <td>
                        <label>
                        <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">
                        Eliminar</a>
                        </label>
                  {% else %}
                  <tr class="danger">
                    <td>{{u.username}}</td>
                    <td>{{u.first_name}}</td>
                    <td>{{u.last_name}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <label>
                        <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">    
                        Eliminar</a>
                        </label>
                  {% endif%}
                    </td>
              {% endfor %}
              </tr>
              </td>
              </tr>
              </table>
        </form>
      
        <!--inicio modal--> 
          <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">

                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2">Confirmación</h4>
                </div>
                <div class="modal-body">
                   ¿Seguro que desea eliminar el usuario? 
                </div>
                <form method='post' action="{% url 'usuario:deluser' %}">
                {% csrf_token %}
                <input type="hidden" id="idusuario" name="idusuario"/>
                <div class="modal-footer">
                  <button type="button" onclick="javascript:window.location.reload()" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <button type="submit"  class="btn btn-default">Aceptar</button>
                </div>
                </form>
               </div>
            </div>
          </div>
          </div>
          </div>
          <!--fin modal--> 

          <br><br><br><br><br><br><br><br><br><br>
          <br>
</div>
{% endblock %}

cumboto-interfaz/cumboto_Front-End/usuario/templates/admin.editclave.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block content %}
<script type='text/javascript'>
$(document).ready(function() {
  $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {
    var data_id = '';
    if (typeof $(this).data('user-id') !== 'undefined') {
      data_id = $(this).data('user-id');
    }
    $('#idusuario').val(data_id);
  });
  })
</script>
<script>
$('#myModal').on('hidden', function () {
  document.location.reload();
})
</script>
      <div class="x_panel">
       <div class="row">
                <br>
                <div class="col-md-4">
                   <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
                </div>
                <div class="col-md-8"></div>
           </div>
      <div class="row">
      <div class="col-md-12" align="center">
      <h1>Cambiar Contraseña</h1>
        <hr>
         <form action="" method="POST">
                   {% csrf_token %}
              <table class="table table-bordered">
                  <tr>
                    <th align="center">Usuario</th>
                    <th align="center">Nombres</th>
                    <th align="center">Apellidos</th>
                    <th align="center">Correo</th>
                    <th align="center">Estatus</th>
                    <th align="center">Opciones</th>
                  </tr>
              {% for u in users %}
              {% if u.is_active%}
              <tr class="bg-success">
                    <td>{{u.username}}</td>
                    <td>{{u.first_name}}</td>
                    <td>{{u.last_name}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
              <td>
                        <label>
                        <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">
                        Cambiar</a>
                        </label>
                  {% else %}
                  <tr class="danger">
                    <td>{{u.username}}</td>
                    <td>{{u.first_name}}</td>
                    <td>{{u.last_name}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <label>
                        <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">    
                        Cambiar</a>
                        </label>
                  {% endif%}
                    </td>
              {% endfor %}
              </tr>
              </td>
              </tr>
              </table>
        </form>
      
        <!--inicio modal--> 
          <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">

                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2">Confirmación</h4>
                </div>
                <div class="modal-body">
                   ¿Seguro que desea editar datos del usuario? 
                </div>
                <form method="POST" action="{% url 'usuario:ediclavone' %}">
                {% csrf_token %}
                <input type="hidden" id="idusuario" name="idusuario"/>
                <div class="modal-footer">
                  <button type="button" onclick="javascript:window.location.reload()" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <button type="submit"  class="btn btn-default">Aceptar</button>
                </div>
                </form>
               </div>
            </div>
          </div>
          </div>
          </div>
          <!--fin modal-->

          <br><br><br><br><br><br><br><br><br><br>
          <br>
</div>
{% endblock %}

cumboto-interfaz/cumboto_Front-End/usuario/templates/admin.template.html
{% extends 'base.template.html' %}
{% load static from staticfiles %}
{% block content %}
<script type='text/javascript'>
$(document).ready(function() {
  $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {
    var data_id = '';
    if (typeof $(this).data('user-id') !== 'undefined') {
      data_id = $(this).data('user-id');
    }
    $('#idusuario').val(data_id);
  });
  })
</script>
<script>
$('#myModal').on('hidden', function () {
  document.location.reload();
})
</script>
<div class="x_panel">
  <div class="row">
    <br>
    <div class="col-md-4">
      <img class="img-reponsive" src="{% static 'img/logocumboto.png' %}" align="left">
    </div>
    <div class="col-md-8"></div>
  </div>
  <div class="row">
    <div class="col-md-12" align="center">
      <h1>Control de Usuarios</h1>
      <hr>
      <form action="" method="post">{% csrf_token %}
        <table class="table table-bordered">
          <tr>
            <th align="center">Usuario</th>
            <th align="center">Nombres</th>
            <th align="center">Apellidos</th>
            <th align="center">Correo</th>
            <th align="center">Estatus</th>
            <th align="center">Opciones</th>
          </tr>
          {% for u in users %}
          {% if u.is_active%}
          <tr class="bg-success">
            <td>{{u.username}}</td>
            <td>{{u.first_name}}</td>
            <td>{{u.last_name}}</td>
            <td>{{u.email}}</td>
            <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
            <td>
              <label>
                <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">
                <input type="checkbox" class="js-switch" checked /> Desactivar</a>
              </label>

              <label>
                <a href="{% url 'usuario:admdelusers' %}">| Eliminar</a>
              </label>

              <label>
                <a href="{% url 'usuario:admedusers' %}">| Editar email</a>
              </label>

              <label>
                <a href="{% url 'usuario:admedclav' %}">| Cambiar contraseña</a>
              </label>
  
          {% else %}
          <tr class="danger">
            <td>{{u.username}}</td>
            <td>{{u.first_name}}</td>
            <td>{{u.last_name}}</td>
            <td>{{u.email}}</td>
            <td>{{u.is_active|yesno:"Activo,Inactivo"}}</td>
            <td>
              <label>
                <a href= "#" data-toggle="modal" data-target="#myModal" data-user-id="{{u.id}}">    
                <input type="checkbox" class="js-switch"  /> Activar</a>
              </label>

              <label>
                <a href="{% url 'usuario:admdelusers' %}">| Eliminar</a>
              </label>

              <label>
                <a href="{% url 'usuario:admedusers' %}">| Editar email</a>
              </label>

              <label>
                <a href="{% url 'usuario:admedclav' %}">| Cambiar contraseña</a>
              </label>
          {% endif%}
            </td>
          {% endfor %}
              </tr>
            </td>
          </tr>
        </table>
      </form>
      <!--inicio modal-->
      <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
              </button>
              <h4 class="modal-title" id="myModalLabel2">Confirmación</h4>
            </div>
            <div class="modal-body">
              ¿Desea realizar el cambio de estatus? 
            </div>
            <form method='post' action="{% url 'usuario:changestatus' %}">{% csrf_token %}
              <input type="hidden" id="idusuario" name="idusuario"/>
              <div class="modal-footer">
                <button type="button" onclick="javascript:window.location.reload()" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit"  class="btn btn-default">Aceptar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--fin modal-->
  <br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

cumboto-interfaz/cumboto_Front-End/usuario/templates/base.login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
{% include 'base.head.template.html' %}
{% block content %}
<body class="login" style="background: url({% static 'img/fondo_cumboto4.png' %}) repeat-y fixed center center; -webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
text-align: center;
height: 100%;
width: 100%;
margin: 0px;
background-position: center;">
<div>
  <a class="hiddenanchor" id="signup"></a>
  <a class="hiddenanchor" id="signin"></a>
    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form  class="form-horizontal form-label-left" name="" action="" method="post" >{% csrf_token %}
            <h1>Iniciar sesión</h1>
            <div class="item form-group">
              <input id="id_username" name="username" type="text" class="form-control col-md-5 col-xs-16" placeholder="Usuario" required="required" title="Ingrese su usuario" autofocus>
            </div>
            <div class="item form-group">
              <input id="id_password" name="password" type="password" class="form-control col-md-5 col-xs-16" placeholder="Contraseña" required="required" title="Ingrese su contraseña" autofocus>
            </div>
            {% for msg in messages %}
              {% if msg %}
              <div class="item form-group">
                <div class="oaerror warning">
                  <strong>Alerta: </strong>{{ msg }}
                </div>
              </div>
              {% endif %}
            {% endfor %}
            <div>
              <input class="btn btn-default submit" type="submit" style="margin-left: 115px" value="Iniciar sesión">
            </div>
            <div class="clearfix"></div>
            <div class="separator">
            <p>
              <a href="{% url 'usuario:registro' %}" class="to_register"> Crear una cuenta </a>
              <a href="{% url 'usuario:password_reset' %}" class="to_register"> Recuperar Contraseña </a>
            </p>
            <div class="clearfix"></div>
            <br />
            <div>
              <h1><img src="{% static 'img/logo.png' %}"> Cumboto</h1>
              <p>©2016 Copyleft CENDITEL</p>
            </div>
            </div>
          </form>
        </section>
      </div>
    </div>
</div>
</body>
{% endblock %}
{% include 'base.footer.template.html' %}
</html>

cumboto-interfaz/cumboto_Front-End/usuario/templates/mensaje-activacion.html
Estimado(a): {{ dat_user }}

Tu cuenta ha sido activada, ya puedes ingresar al sistema.

cumboto-interfaz/cumboto_Front-End/usuario/templates/mensaje-desactivacion.html
Estimado(a): {{ dat_user }}

Tu cuenta ha sido desactivada.